const PRIMARY_COLOR = '#313237';
const SECONDARY_COLOR = '#89939A';
const ICONS_COLOR = '#B4BDC3';
const ELEMENTS_COLOR = '#E2E6E9';
const HOVER_COLOR = '#FAFBFC';
const WHITE_COLOR = '#FFFF';
const SUCCESS_COLOR = '#27AE60';
const ERROR_COLOR = '#EB5757';
